export const GET_CITY_FORECAST_REQUEST = "GET_CITY_FORECAST_REQUEST";
export const GET_CITY_FORECAST_SUCCESS = "GET_CITY_FORECAST_SUCCESS";
export const GET_CITY_FORECAST_ERROR = "GET_CITY_FORECAST_ERROR";
